V.Harish
BL.EN.U4AIE22063
Lab-02(06-02-2024)

1.Write a function to calculate the Euclidean distance and Manhattan distance between two vectors. The vectors dimension is variable. Please don’t use any distance calculation functions available in Python.

In [19]:
def calculate_distance(X,Y):   
    if len(X)!=len(Y):      #base condition for distance calculation
        ValueError("Both must have same dimensions")
        
    Euclidean=Euclidean_distance(X,Y)
    Manhottan=Manhottan_distance(X,Y)
    return [Euclidean,Manhottan]

def Euclidean_distance(X,Y):     #sqrt of summation of square of difference of actual and predicted values
    sum_distance=0

    for x,y in zip(X,Y):
        sum_distance+=(x-y)**2   #square of the values
    return sum_distance**0.5    #sqrt of the sum_ditance

def Manhottan_distance(X,Y):        #summation of difference of actual and predicted values
    sum1_distance=0
        
    for x,y in zip(X,Y):
        sum1_distance+=abs(x-y)     #as the distances are always positive,use abs(absolute) difference
    return sum1_distance

X=[9,2,5]
Y=[12,31,25]
Distance=calculate_distance(X,Y)

print(f"Euclidean Distance: {Distance[0]}")
print(f"Manhottan Distance: {Distance[1]}")

Euclidean Distance: 35.35533905932738
Manhottan Distance: 52


2.Write a function to implement k-NN classifier. k is a variable and based on that the count of neighbors should be selected.

In [20]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [21]:
def KnnClassifier(X,Y,k,New_point):
    knn=KNeighborsClassifier(n_neighbors=k)     #creating an object of KNeighborsClassifier with 'k' as the value of n_neighbors parameter
    knn.fit(X,Y)        # Fitting the model with the training data(X) and corresponding labels(Y)
    return knn.predict(New_point)[0]

X=np.array([[1,2,3],[4,5,6],[2,3,5],[7,3,1],[2,3,2],[1,2,3]])
Y=np.array(["A","B","C","B","A","C"])
New_point=np.array([[5,4,8]])
KnnClassifier(X,Y,4,New_point)

'C'

3.Write a function to convert categorical variables to numeric using label encoding. Don’t use any existing functionalities.

In [22]:
def Label_Encode(Data):
    Classes=[]
    for data in Data:
        if data not in Classes:     #check if the class already exist
            Classes.append(data)        #if it doesnt exist,then add inorder to keep only unique class 
            
    encode_data=[]
    for data in Data:
        index=Classes.index(data)       #index of the class in the list of unique classes
        encode_data.append(index)       #assign the index to the corresponding data
        
    return encode_data
        
Data=["India","Australia","Japan","China","US","Russia"]
Label_Encode(Data)

    

[0, 1, 2, 3, 4, 5]

4.Write a function to convert categorical variables to numeric using One-Hotencoding. Don’t use any existing functionalities.

In [23]:
def One_hot_Encode(Data,Classes):
    n=len(Classes)
    i=0
    encoded_data=[]
    for data in Data:
        encode_data=np.zeros(n)
        if data in Classes:
            index=Classes.index(data)   #Find the index of the data point in the list of classes
            encode_data[index]=1        #Assign the corresponding index in the one-hot encoded array to 1
            encoded_data.append(encode_data)        #one-hot encoding for the particular class
        i+=1
        
    return encoded_data

Data=["India","Australia","US","China","Australia","China","India","India"]
Classes=["India","Australia","US","China"]
One_hot_Encode(Data,Classes)

[array([1., 0., 0., 0.]),
 array([0., 1., 0., 0.]),
 array([0., 0., 1., 0.]),
 array([0., 0., 0., 1.]),
 array([0., 1., 0., 0.]),
 array([0., 0., 0., 1.]),
 array([1., 0., 0., 0.]),
 array([1., 0., 0., 0.])]